### ISSUE TITLE
Does not work with blender 2.78

### ISSUE THREAD

**Issue by tim-we** [09th/YABEE#27]
Trying to export a simple plane I got this error:
`AttributeError: 'BlendData' object has no attribute 'scripts'`
in egg_writer.py:1097

Changing it from
`bpy.data.scripts, bpy.data.shape_keys, bpy.data.sounds,`
to
`bpy.data.shape_keys, bpy.data.sounds,`

fixed that error for me.

**Comment by rdb** [comment]
Apparently `bpy.data.scripts` has been deprecated for a while and was removed in Blender 2.77.

**Comment by rdb** [comment]
You must be using an outdated version of YABEE.  This issue was already fixed a while ago:

https://github.com/09th/YABEE/commit/0530d3da2add01e3051402324b14f3207bda6892
