### ISSUE TITLE
Needs updating to work in Blender 2.8

### ISSUE THREAD

**Issue by BrettWitty** [09th/YABEE#40]
I know that this plugin is written for Blender 2.5-2.7, but it may be worthwhile preparing for the forthcoming Blender 2.8.

Guidelines on things to be changed: https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons

I attempted to make the changes myself, but I can't get it to appear in the export menu.

**Comment by scott--** [comment]
I was also trying to get this script to work in Blender 2.8.

I got the menu option to appear by changing the following:

bl_info version to (2, 80, 0)
INFO_MT_file_export is now TOPBAR_MT_file_export
removing bpy.utils.register_module / bpy.utils.unregister_module
registering a bunch of classes instead

Unfortunately now I'm getting:

```
location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/scott/.config/blender/2.80/scripts/addons/YABEE-master/__init__.py", line 434, in draw
    context.scene.yabee_settings.draw(self.layout)
  File "/home/scott/.config/blender/2.80/scripts/addons/YABEE-master/__init__.py", line 171, in draw
    layout.row().label('Animation:')
TypeError: UILayout.label(): required parameter "text" to be a keyword argument!

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/scott/.config/blender/2.80/scripts/addons/YABEE-master/__init__.py", line 410, in execute
    sett.opt_force_export_vertex_colors,)
  File "/home/scott/.config/blender/2.80/scripts/addons/YABEE-master/yabee_libs/egg_writer.py", line 1629, in write_out
    for tex in obj.texture_slots.values():
AttributeError: 'Material' object has no attribute 'texture_slots'
```

**Comment by HeadClot** [comment]
Hey just thought I would give this a bump as Blender 2.8 stable comes out in July.

**Comment by Moguri** [comment]
A list of changes and some ideas on maintaining 2.7 and 2.8 support in the same code base can be found [here](https://theduckcow.com/2019/update-addons-both-blender-28-and-27-support/)

**Comment by david-ragazzi** [comment]
Hi guys, do you have any plans to this?

**Comment by kergalym** [comment]
I managed to get it work in Blender 2.80 (some features are missing yet) 
https://github.com/kergalym/YABEE

**Comment by HeadClot** [comment]
Thank you @kergalym
